language: java

jdk:
  - openjdk8

services:
  - mysql
  
dist: trusty

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS worklifebalance'
  - mysql -u root -e 'CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';'
  - mysql -u root -e 'GRANT ALL ON worklifebalance.* TO 'root'@'localhost';'
  - mysql -u root --default-character-set=utf8 worklifebalance < database/DatabaseCreator.sql
  
cache:
  bundler: true
  directories:
    - ${HOME}/.m2

script: | 
    mvn test
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: never
