language: java

jdk:
  - openjdk8

sudo: false

cache:
  bundler: true
  directories:
    - ${HOME}/.m2

script: | 
    mvn --version && mvn clean test verify -B
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: never
