language: java

jdk:
  - openjdk8

services:
  - mysql

sudo: false

cache:
  bundler: true
  directories:
    - ${HOME}/.m2

script: | 
    mvn test
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: never
