language: java

jdk:
  - openjdk8

services:
  - mysql
  
dist: trusty

sudo: required

addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client

before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS worklifebalance'
  - mysql -u root -e "SET PASSWORD FOR 'root' = PASSWORD('root');"
  - mysql -u root -e "GRANT ALL ON worklifebalance.* TO 'root'@'localhost';"
  FLUSH PRIVILEGES;
  - mysql -u root --default-character-set=utf8 worklifebalance < database/DatabaseCreator.sql
  
cache:
  bundler: true
  directories:
    - ${HOME}/.m2

script: | 
    mvn test
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: never
