language: java

jdk:
  - openjdk8

services:
  - mysql

before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade
- sudo service mysql restart

cache:
  bundler: true
  directories:
    - ${HOME}/.m2

script: | 
    mvn test
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: never
