language: java

jdk:
  - openjdk8

services:
  - mysql

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  
cache:
  bundler: true
  directories:
    - ${HOME}/.m2

script: | 
    mvn test
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: never
